nessus:
  url: "https://<nessus-server-ip>:8834"

scan_templates:
  windows_stig: "<windows-stig-template-uuid>"
  esxi_stig: "<esxi-stig-template-uuid>"
  network_stig: "<network-stig-template-uuid>"
